export const CREATE_STUDENT = 'CREATE_STUDENT';
export const GET_STUDENT_SUCCESS = 'GET_STUDENT_SUCCESS';
export const GET_STUDENT_FAILURE = 'GET_STUDENT_FAILURE';

export const CREATE_DOCTOR = 'CREATE_DOCTOR';
export const GET_DOCTOR_SUCCESS = 'GET_DOCTOR_SUCCESS';
export const GET_DOCTOR_FAILURE = 'GET_DOCTOR_FAILURE';